/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'barricadeDoor' : IDL.Func([IDL.Text], [], []),
  'enterSaveSpot' : IDL.Func([], [], []),
  'exitSaveSpot' : IDL.Func([], [], []),
  'findCode' : IDL.Func([], [], []),
  'findKeycard' : IDL.Func([], [], []),
  'getPlayerState' : IDL.Func(
      [],
      [IDL.Nat, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'setScene' : IDL.Func([IDL.Text], [], []),
  'unbarricadeDoor' : IDL.Func([IDL.Text], [], []),
  'updateStress' : IDL.Func([IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'barricadeDoor' : IDL.Func([IDL.Text], [], []),
    'enterSaveSpot' : IDL.Func([], [], []),
    'exitSaveSpot' : IDL.Func([], [], []),
    'findCode' : IDL.Func([], [], []),
    'findKeycard' : IDL.Func([], [], []),
    'getPlayerState' : IDL.Func(
        [],
        [IDL.Nat, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'setScene' : IDL.Func([IDL.Text], [], []),
    'unbarricadeDoor' : IDL.Func([IDL.Text], [], []),
    'updateStress' : IDL.Func([IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };